/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as CollegeRouteImport } from './routes/college'
import { Route as CentralRouteImport } from './routes/central'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CollegeIndexRouteImport } from './routes/college.index'
import { Route as CentralIndexRouteImport } from './routes/central.index'
import { Route as StudentSplatRouteImport } from './routes/student.$'
import { Route as CollegeSplatRouteImport } from './routes/college.$'
import { Route as CentralSplatRouteImport } from './routes/central.$'
import { Route as StudentProjectsProjectIdRouteImport } from './routes/student.projects.$projectId'
import { Route as CollegeStudentsStudentIdRouteImport } from './routes/college.students.$studentId'
import { Route as CollegeProjectsProjectIdRouteImport } from './routes/college.projects.$projectId'
import { Route as CollegeCollegesCollegeIdRouteImport } from './routes/college.colleges.$collegeId'
import { Route as CentralStudentsStudentIdRouteImport } from './routes/central.students.$studentId'
import { Route as CentralProjectsProjectIdRouteImport } from './routes/central.projects.$projectId'
import { Route as CentralEcosystemCollegesRouteImport } from './routes/central.ecosystem.colleges'
import { Route as CentralCollegesCollegeIdRouteImport } from './routes/central.colleges.$collegeId'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api/public/seed-demo'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeRoute = CollegeRouteImport.update({
  id: '/college',
  path: '/college',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CollegeIndexRoute = CollegeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollegeRoute,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralRoute,
} as any)
const StudentSplatRoute = StudentSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => StudentRoute,
} as any)
const CollegeSplatRoute = CollegeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CollegeRoute,
} as any)
const CentralSplatRoute = CentralSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => CentralRoute,
} as any)
const StudentProjectsProjectIdRoute =
  StudentProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => StudentRoute,
  } as any)
const CollegeStudentsStudentIdRoute =
  CollegeStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => CollegeRoute,
  } as any)
const CollegeProjectsProjectIdRoute =
  CollegeProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => CollegeRoute,
  } as any)
const CollegeCollegesCollegeIdRoute =
  CollegeCollegesCollegeIdRouteImport.update({
    id: '/colleges/$collegeId',
    path: '/colleges/$collegeId',
    getParentRoute: () => CollegeRoute,
  } as any)
const CentralStudentsStudentIdRoute =
  CentralStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => CentralRoute,
  } as any)
const CentralProjectsProjectIdRoute =
  CentralProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => CentralRoute,
  } as any)
const CentralEcosystemCollegesRoute =
  CentralEcosystemCollegesRouteImport.update({
    id: '/ecosystem/colleges',
    path: '/ecosystem/colleges',
    getParentRoute: () => CentralRoute,
  } as any)
const CentralCollegesCollegeIdRoute =
  CentralCollegesCollegeIdRouteImport.update({
    id: '/colleges/$collegeId',
    path: '/colleges/$collegeId',
    getParentRoute: () => CentralRoute,
  } as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/central': typeof CentralRouteWithChildren
  '/college': typeof CollegeRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/central/$': typeof CentralSplatRoute
  '/college/$': typeof CollegeSplatRoute
  '/student/$': typeof StudentSplatRoute
  '/central/': typeof CentralIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/central/colleges/$collegeId': typeof CentralCollegesCollegeIdRoute
  '/central/ecosystem/colleges': typeof CentralEcosystemCollegesRoute
  '/central/projects/$projectId': typeof CentralProjectsProjectIdRoute
  '/central/students/$studentId': typeof CentralStudentsStudentIdRoute
  '/college/colleges/$collegeId': typeof CollegeCollegesCollegeIdRoute
  '/college/projects/$projectId': typeof CollegeProjectsProjectIdRoute
  '/college/students/$studentId': typeof CollegeStudentsStudentIdRoute
  '/student/projects/$projectId': typeof StudentProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/central/$': typeof CentralSplatRoute
  '/college/$': typeof CollegeSplatRoute
  '/student/$': typeof StudentSplatRoute
  '/central': typeof CentralIndexRoute
  '/college': typeof CollegeIndexRoute
  '/student': typeof StudentIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/central/colleges/$collegeId': typeof CentralCollegesCollegeIdRoute
  '/central/ecosystem/colleges': typeof CentralEcosystemCollegesRoute
  '/central/projects/$projectId': typeof CentralProjectsProjectIdRoute
  '/central/students/$studentId': typeof CentralStudentsStudentIdRoute
  '/college/colleges/$collegeId': typeof CollegeCollegesCollegeIdRoute
  '/college/projects/$projectId': typeof CollegeProjectsProjectIdRoute
  '/college/students/$studentId': typeof CollegeStudentsStudentIdRoute
  '/student/projects/$projectId': typeof StudentProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/central': typeof CentralRouteWithChildren
  '/college': typeof CollegeRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/central/$': typeof CentralSplatRoute
  '/college/$': typeof CollegeSplatRoute
  '/student/$': typeof StudentSplatRoute
  '/central/': typeof CentralIndexRoute
  '/college/': typeof CollegeIndexRoute
  '/student/': typeof StudentIndexRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/central/colleges/$collegeId': typeof CentralCollegesCollegeIdRoute
  '/central/ecosystem/colleges': typeof CentralEcosystemCollegesRoute
  '/central/projects/$projectId': typeof CentralProjectsProjectIdRoute
  '/central/students/$studentId': typeof CentralStudentsStudentIdRoute
  '/college/colleges/$collegeId': typeof CollegeCollegesCollegeIdRoute
  '/college/projects/$projectId': typeof CollegeProjectsProjectIdRoute
  '/college/students/$studentId': typeof CollegeStudentsStudentIdRoute
  '/student/projects/$projectId': typeof StudentProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/central'
    | '/college'
    | '/student'
    | '/central/$'
    | '/college/$'
    | '/student/$'
    | '/central/'
    | '/college/'
    | '/student/'
    | '/api/public/seed-demo'
    | '/central/colleges/$collegeId'
    | '/central/ecosystem/colleges'
    | '/central/projects/$projectId'
    | '/central/students/$studentId'
    | '/college/colleges/$collegeId'
    | '/college/projects/$projectId'
    | '/college/students/$studentId'
    | '/student/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/central/$'
    | '/college/$'
    | '/student/$'
    | '/central'
    | '/college'
    | '/student'
    | '/api/public/seed-demo'
    | '/central/colleges/$collegeId'
    | '/central/ecosystem/colleges'
    | '/central/projects/$projectId'
    | '/central/students/$studentId'
    | '/college/colleges/$collegeId'
    | '/college/projects/$projectId'
    | '/college/students/$studentId'
    | '/student/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/central'
    | '/college'
    | '/student'
    | '/central/$'
    | '/college/$'
    | '/student/$'
    | '/central/'
    | '/college/'
    | '/student/'
    | '/api/public/seed-demo'
    | '/central/colleges/$collegeId'
    | '/central/ecosystem/colleges'
    | '/central/projects/$projectId'
    | '/central/students/$studentId'
    | '/college/colleges/$collegeId'
    | '/college/projects/$projectId'
    | '/college/students/$studentId'
    | '/student/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CentralRoute: typeof CentralRouteWithChildren
  CollegeRoute: typeof CollegeRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college': {
      id: '/college'
      path: '/college'
      fullPath: '/college'
      preLoaderRoute: typeof CollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/college/': {
      id: '/college/'
      path: '/'
      fullPath: '/college/'
      preLoaderRoute: typeof CollegeIndexRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/central/': {
      id: '/central/'
      path: '/'
      fullPath: '/central/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof CentralRoute
    }
    '/student/$': {
      id: '/student/$'
      path: '/$'
      fullPath: '/student/$'
      preLoaderRoute: typeof StudentSplatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/college/$': {
      id: '/college/$'
      path: '/$'
      fullPath: '/college/$'
      preLoaderRoute: typeof CollegeSplatRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/central/$': {
      id: '/central/$'
      path: '/$'
      fullPath: '/central/$'
      preLoaderRoute: typeof CentralSplatRouteImport
      parentRoute: typeof CentralRoute
    }
    '/student/projects/$projectId': {
      id: '/student/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/student/projects/$projectId'
      preLoaderRoute: typeof StudentProjectsProjectIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/college/students/$studentId': {
      id: '/college/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/college/students/$studentId'
      preLoaderRoute: typeof CollegeStudentsStudentIdRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/projects/$projectId': {
      id: '/college/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/college/projects/$projectId'
      preLoaderRoute: typeof CollegeProjectsProjectIdRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/college/colleges/$collegeId': {
      id: '/college/colleges/$collegeId'
      path: '/colleges/$collegeId'
      fullPath: '/college/colleges/$collegeId'
      preLoaderRoute: typeof CollegeCollegesCollegeIdRouteImport
      parentRoute: typeof CollegeRoute
    }
    '/central/students/$studentId': {
      id: '/central/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/central/students/$studentId'
      preLoaderRoute: typeof CentralStudentsStudentIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/central/projects/$projectId': {
      id: '/central/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/central/projects/$projectId'
      preLoaderRoute: typeof CentralProjectsProjectIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/central/ecosystem/colleges': {
      id: '/central/ecosystem/colleges'
      path: '/ecosystem/colleges'
      fullPath: '/central/ecosystem/colleges'
      preLoaderRoute: typeof CentralEcosystemCollegesRouteImport
      parentRoute: typeof CentralRoute
    }
    '/central/colleges/$collegeId': {
      id: '/central/colleges/$collegeId'
      path: '/colleges/$collegeId'
      fullPath: '/central/colleges/$collegeId'
      preLoaderRoute: typeof CentralCollegesCollegeIdRouteImport
      parentRoute: typeof CentralRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CentralRouteChildren {
  CentralSplatRoute: typeof CentralSplatRoute
  CentralIndexRoute: typeof CentralIndexRoute
  CentralCollegesCollegeIdRoute: typeof CentralCollegesCollegeIdRoute
  CentralEcosystemCollegesRoute: typeof CentralEcosystemCollegesRoute
  CentralProjectsProjectIdRoute: typeof CentralProjectsProjectIdRoute
  CentralStudentsStudentIdRoute: typeof CentralStudentsStudentIdRoute
}

const CentralRouteChildren: CentralRouteChildren = {
  CentralSplatRoute: CentralSplatRoute,
  CentralIndexRoute: CentralIndexRoute,
  CentralCollegesCollegeIdRoute: CentralCollegesCollegeIdRoute,
  CentralEcosystemCollegesRoute: CentralEcosystemCollegesRoute,
  CentralProjectsProjectIdRoute: CentralProjectsProjectIdRoute,
  CentralStudentsStudentIdRoute: CentralStudentsStudentIdRoute,
}

const CentralRouteWithChildren =
  CentralRoute._addFileChildren(CentralRouteChildren)

interface CollegeRouteChildren {
  CollegeSplatRoute: typeof CollegeSplatRoute
  CollegeIndexRoute: typeof CollegeIndexRoute
  CollegeCollegesCollegeIdRoute: typeof CollegeCollegesCollegeIdRoute
  CollegeProjectsProjectIdRoute: typeof CollegeProjectsProjectIdRoute
  CollegeStudentsStudentIdRoute: typeof CollegeStudentsStudentIdRoute
}

const CollegeRouteChildren: CollegeRouteChildren = {
  CollegeSplatRoute: CollegeSplatRoute,
  CollegeIndexRoute: CollegeIndexRoute,
  CollegeCollegesCollegeIdRoute: CollegeCollegesCollegeIdRoute,
  CollegeProjectsProjectIdRoute: CollegeProjectsProjectIdRoute,
  CollegeStudentsStudentIdRoute: CollegeStudentsStudentIdRoute,
}

const CollegeRouteWithChildren =
  CollegeRoute._addFileChildren(CollegeRouteChildren)

interface StudentRouteChildren {
  StudentSplatRoute: typeof StudentSplatRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentProjectsProjectIdRoute: typeof StudentProjectsProjectIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentSplatRoute: StudentSplatRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentProjectsProjectIdRoute: StudentProjectsProjectIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CentralRoute: CentralRouteWithChildren,
  CollegeRoute: CollegeRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
